/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PruebaFTP;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jose.paredes
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    private DefaultListModel listModel = new DefaultListModel(); 
    private ClienteFTP ftp = new ClienteFTP();
    private boolean Conectado = false;
    private String rutaDescarga;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void cargarListaArchivos(){
        
        try {
            listModel.removeAllElements();
            ListaArchivos.setModel(listModel);
            String lista[] = ftp.listNames();
            for(String arch: lista) 
                listModel.addElement(arch);
            ListaArchivos.setModel(listModel);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Servidor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Conectar = new javax.swing.JButton();
        EstadoConexion = new javax.swing.JLabel();
        Desconectar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        URLDescargar = new javax.swing.JTextField();
        CambiarRuta = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        URLFicheroZIPEnviar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NombreFicheroZIPEnviar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SubirArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaArchivos = new javax.swing.JList<>();
        DescargarArchivo = new javax.swing.JButton();
        BorrarArchivo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        URLServidor = new javax.swing.JTextField();
        CambiarRutaServidor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente FTP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        Servidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServidorActionPerformed(evt);
            }
        });

        jLabel1.setText("Servidor");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Conectar.setText("Conectar");
        Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarActionPerformed(evt);
            }
        });

        EstadoConexion.setText("Estado: No Conectado");

        Desconectar.setText("Desconectar");
        Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesconectarActionPerformed(evt);
            }
        });

        jLabel4.setText("Descargar fichero");

        jLabel7.setText("URL ruta de descarga");

        URLDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLDescargarActionPerformed(evt);
            }
        });

        CambiarRuta.setText("Cambiar Ruta de Descarga");
        CambiarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarRutaActionPerformed(evt);
            }
        });

        jLabel9.setText("Subir un Archivo");

        URLFicheroZIPEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLFicheroZIPEnviarActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre");

        NombreFicheroZIPEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFicheroZIPEnviarActionPerformed(evt);
            }
        });

        jLabel11.setText("Ubicacion Archivo");

        SubirArchivo.setText("Subir Archivo");
        SubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirArchivoActionPerformed(evt);
            }
        });

        ListaArchivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaArchivos.setToolTipText("");
        ListaArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaArchivosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaArchivos);

        DescargarArchivo.setText("Descargar");
        DescargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargarArchivoActionPerformed(evt);
            }
        });

        BorrarArchivo.setText("Borrar");
        BorrarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarArchivoActionPerformed(evt);
            }
        });

        jLabel12.setText("URL ruta de Servidor");

        URLServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLServidorActionPerformed(evt);
            }
        });

        CambiarRutaServidor.setText("Cambiar Ruta del Servidor");
        CambiarRutaServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarRutaServidorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mi cliente FTP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(URLServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CambiarRutaServidor))
                    .addComponent(EstadoConexion)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(URLDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CambiarRuta))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Conectar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desconectar))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DescargarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BorrarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreFicheroZIPEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(URLFicheroZIPEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubirArchivo)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstadoConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Conectar)
                    .addComponent(Desconectar)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URLDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambiarRuta)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URLServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambiarRutaServidor)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreFicheroZIPEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(URLFicheroZIPEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubirArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DescargarArchivo)
                        .addGap(18, 18, 18)
                        .addComponent(BorrarArchivo)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServidorActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesconectarActionPerformed
           if( Conectado ){
                if( ftp.desconectar() ){
                    EstadoConexion.setText("Estado: No conectado");
                    JOptionPane.showMessageDialog(null, "Desconexion Exitosa");
                } else {
                    EstadoConexion.setText("Estado: No conectado");
                    JOptionPane.showMessageDialog(null, "Error al desconectar");
                }
           } else {
               JOptionPane.showMessageDialog(null, "Servidor no Conectado");
           }
    }//GEN-LAST:event_DesconectarActionPerformed

    private void URLDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLDescargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLDescargarActionPerformed

    private void URLFicheroZIPEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLFicheroZIPEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLFicheroZIPEnviarActionPerformed

    private void NombreFicheroZIPEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFicheroZIPEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFicheroZIPEnviarActionPerformed

    private void ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarActionPerformed
        if( Servidor.getText().length() > 0 && Usuario.getText().length() > 0 && Contraseña.getText().length() > 0 ){
            boolean resp = ftp.conectar(Servidor.getText(), Usuario.getText(), Contraseña.getText());
            if(resp){
                Conectado = true;
                EstadoConexion.setText("Estado: Conectado");
                JOptionPane.showMessageDialog(null, "Conexion Exitosa");
                cargarListaArchivos();
            }else{
                JOptionPane.showMessageDialog(null, "Servidor, Usuario o contraseña incorrectos.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Datos ingresados incorrectos");
        }
    }//GEN-LAST:event_ConectarActionPerformed

    private void CambiarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarRutaActionPerformed
        if( Conectado ){
            rutaDescarga = URLDescargar.getText();
            URLDescargar.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Servidor Desconectado");
        }
    }//GEN-LAST:event_CambiarRutaActionPerformed

    private void SubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirArchivoActionPerformed
        if( Conectado ){
            if ( ftp.subirFichero( NombreFicheroZIPEnviar.getText(), URLFicheroZIPEnviar.getText() ) ){
                JOptionPane.showMessageDialog(null, "Archivo Subido con exito");
            }else{
                JOptionPane.showMessageDialog(null, "Error al Subir el archivo");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Servidor Desconectado");
        }
    }//GEN-LAST:event_SubirArchivoActionPerformed

    private void ListaArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaArchivosValueChanged
        ListaArchivos.getSelectedValue();
    }//GEN-LAST:event_ListaArchivosValueChanged

    private void DescargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargarArchivoActionPerformed
        if( Conectado ){
            if( ftp.descargaFich(ListaArchivos.getSelectedValue(), rutaDescarga))
                JOptionPane.showMessageDialog(null, "Archivo descargado exitosamente");
            else
                JOptionPane.showMessageDialog(null, "Error al descargar el archivo");
        }else{
            JOptionPane.showMessageDialog(null, "Servidor Desconectado");
        }
    }//GEN-LAST:event_DescargarArchivoActionPerformed

    private void BorrarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarArchivoActionPerformed
        if( Conectado ){
            if( ftp.borrarFichero(ListaArchivos.getSelectedValue()))
                JOptionPane.showMessageDialog(null, "Archivo Borrado exitosamente");
            else
                JOptionPane.showMessageDialog(null, "Error al Borrado el archivo");
        }else{
            JOptionPane.showMessageDialog(null, "Servidor Desconectado");
        }
    }//GEN-LAST:event_BorrarArchivoActionPerformed

    private void URLServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLServidorActionPerformed

    private void CambiarRutaServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarRutaServidorActionPerformed
         if( Conectado ){
            if( ftp.cambiarDirectorio(URLServidor.getText()) )
                JOptionPane.showMessageDialog(null, "Directorio Cambiado exitosamente");
            else
                JOptionPane.showMessageDialog(null, "Error al Cambiar el directorio");
        }else{
            JOptionPane.showMessageDialog(null, "Servidor Desconectado");
        }    
        
    }//GEN-LAST:event_CambiarRutaServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarArchivo;
    private javax.swing.JButton CambiarRuta;
    private javax.swing.JButton CambiarRutaServidor;
    private javax.swing.JButton Conectar;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JButton DescargarArchivo;
    private javax.swing.JButton Desconectar;
    private javax.swing.JLabel EstadoConexion;
    private javax.swing.JList<String> ListaArchivos;
    private javax.swing.JTextField NombreFicheroZIPEnviar;
    private javax.swing.JTextField Servidor;
    private javax.swing.JButton SubirArchivo;
    private javax.swing.JTextField URLDescargar;
    private javax.swing.JTextField URLFicheroZIPEnviar;
    private javax.swing.JTextField URLServidor;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
